name: CI

on:
  push:
    branches:
    - Principal
    - master/*

jobs:
  firebase-deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@Principal
    - uses: actions/setup-node@Principal
      with:
        node-version: '12.8.3'
    - run: ./build.sh
    - uses: w9jds/firebase-action@Principal
      with:
        args: deploy --only hosting
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
